# -*- coding: utf-8 -*-
"""Spark_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6Js-lwude-T7HXjt1NHENAkj-bvxJEA
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Spark Assignment") \
    .master("local[*]") \
    .getOrCreate()

print("Spark Started Successfully!")

df = spark.read.csv(
    "/content/Employee.csv",
    header=True,
    inferSchema=True
)

df.show()

df.printSchema()

df.columns

df.select(
    "Education",
    "City",
    "Age",
    "PaymentTier"
).show()

df.filter(df.Age > 30).show()

df.filter(df.PaymentTier == 3).show()

df = df.withColumnRenamed(
    "PaymentTier",
    "SalaryTier"
)

df.show()

from pyspark.sql.functions import lit

df = df.withColumn(
    "Country",
    lit("India")
)

df.show()

from pyspark.sql.functions import col

df = df.withColumn(
    "AgeAfter5Years",
    col("Age") + 5
)

df.show()

df.na.drop().show()

df.na.fill(0).show()

df = df.dropDuplicates()

df.count()

df.orderBy("Age").show()

df.orderBy(df.Age.desc()).show()

from pyspark.sql.functions import avg

df.groupBy("City").agg(
    avg("Age").alias("AverageAge")
).show()

filtered = df.filter(df.Age > 25)

print("Transformation Created")

filtered.show()

df.write \
.mode("overwrite") \
.option("header", True) \
.csv("/content/output_csv")

df.write \
.mode("overwrite") \
.parquet("/content/output_parquet")

parquet_df = spark.read.parquet("/content/output_parquet")

parquet_df.show()

spark.stop()

